### ISSUE TITLE
muchos a muchos de una misma tabla

### ISSUE THREAD

**Issue by Josejeth** [aspnet/EntityFramework.Docs.es-es#13]
Mi duda viene a ser como hacer una relación muchos a muchos de una misma tabla, por ejemplo, imaginemos que en el ejemplo de varios a varios que tienen aquí mismo quieren relacionar post en varias partes y todas pertenecen al mismo post. Es decir, el post "Guia Automovilismo 1","Guia Automovilismo 2" y demás serían post relacionados.

He probado la solución que tienen del post y funciona pero cuando lo intento relacionarlo consigo mismo me da error. 

Gracias por leerme.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relaciones - EF Core](https://docs.microsoft.com/es-es/ef/core/modeling/relationships#feedback)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs.es-es/blob/live/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by srvbpigh** [comment]
Hello, @Josejeth
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @Josejeth

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by IbaiCarreno** [comment]
Hola, muy buenas, yo tengo la misma duda, ¿Cómo sería la relación n a m consigo misma? Imaginando tener una tabla PRODUCTO, realizar una relación n a m consigo misma de tal forma que la tabla que se crearía se denominaría COMPONENTE, la cual guardaría IDARTICULO e IDARTICULOPADRE respectivamente, con la finalidad de que un ARTICULO pueda tener un ARTICULO PADRE, es decir, el ARTICULO: RUEDA, tendría un ARTICULO PADRE: bicicleta.

No sé si me he explicado de manera correcta, pero no encuentro la manera de vincular esta relación mediante el ENTITY FRAMEWORK.

Un cordial saludo,

Ibai.
